#!/bin/bash
#
#this program reads parameters from command line, make their average
#actually this is written under the course porgramme
#
#written by yagnesh on 09.07.2008

#intializing the sum 
sum=0
nop=$#   # setting no of arg variable

#if no arguments
if [ "$1" = "" ]
then
    echo "Average is: 0 "
    exit
fi

# taking the sum of all arguments
for arg in $*
do
	sum=`expr $sum + $arg`
done

#calculating the average
avg=`expr $sum / $nop`

echo "Average is: $avg "

#this is added in lappy