#!/usr/bin/env bash
#
# last modified: 2011-12-04 23:31

# clock - A bash clock that can run in your terminal window.
clock ()
{
    while true;
    do
        clear;
        echo "===========";
        date +"%r";
        echo "===========";
        sleep 1;
    done
}
