#!/bin/bash

#this is part bash course project
#
#this is for maintaining a data base of personal contacts
#

#setting variable that containg the database file name
DBdir=$HOME/cdb
fname=$DBdir/names.dat

#
#if dir & file does not exist., create it
#
[ ! -d $DBdir ] && mkdir $DBdir
[ ! -f $fname ] && > $fname

while true
do

#welcome message
clear
echo -e "\n\t\tWELCOME TO THE USER DETAILS DATA BASE"
echo -e  "\t\t\t\tMAIN MENU\n\n"
#asking user for job
echo -e "What you would like to do this time?\n"

#Displaying the option to the user
echo -e  "Give a number according to the Options below\n"

echo -e "\t   Create->1 "
echo -e "\t     View->2 "
echo -e "\t   Search->3 "
echo -e "\t   Delete->4 "
echo -e "\t     Quit->q "
read act junk;


#Identifying the given job
case "$act" in

    "" )
      echo "You did not enter any option"
      echo "Bye, have a nice a day"
      exit
    ;;

    0 )
     exit    
    ;;
    
    1 )
      #Collecting the data from the user
      #
      echo -n  "  Please Enter Your name : "; read name
      echo -n  "      Enter Your surname : "; read sname
      echo -n  "		 Address : "; read add
      echo -n  "		    city : "; read city
      echo -n  "		   state : "; read state
      echo -n  "		zip code : "; read zip

      #writing into the data base of user details
      echo $name : $sname : $add : $city : $state : $zip >> $fname
    ;;

    2 )
      cat $fname
      ;;

    3 )
      echo "This Search case is under construction., Than Q"
      ;;

    4 )
      echo "this delete case is under construction., Than Q"
      ;;
    q*|Q* )
      exit 0
      ;;
    * )
      echo "plz enter a no betweet 1 to 2 ^G"
      ;;
esac

#setting a optional ending loop
echo "Hit ENTER to continue
read junk

done


# showing the record in the end., and displaying the no of records present in the data base
(
echo
echo "The records presently available in the database:" 
echo
cat $fname
echo
echo "the total no of entries in the data base is: "
echo `cat "$fname" | wc -l`
) | more

echo "Than Q ., Have a Nice Day"


