#!/usr/bin/env bash
#
# Define a word - USAGE: define dog
define ()
{
    echo lynx -dump "http://www.google.com/search?hl=en&q=define%3A+${1}" # | grep -m 3 -w "*"  | sed 's/;/ -/g' | cut -d- -f1 > /tmp/templookup.txt
    if [[ -s  /tmp/templookup.txt ]] ;then
        until ! read response
        do
            echo "${response}"
        done < /tmp/templookup.txt
    else
        echo "Sorry $USER, I can't find the term \"${1} \""
    fi
    \rm -f /tmp/templookup.txt
}

define $@
