#!/usr/bin/env bash
# -*- mode: shell-script; -*-
#---------------------------------------------------------------------------
# Author: yagnesh raghava yakkala  Email: yagneshmsc@NOSPAMgmail.com
# DATE: 2010-09-17
# Purpose: mount remote folder locally(~/far_projects) using sshfs, this is
#   like alias alomst
#
# Time-stamp: <2001-02-18 10:20:51>
#---------------------------------------------------------------------------

function usage() {     # let the user know how to use this
    echo USAGE: "$1 <$USER@remote:/projects>"
}

ARGCOUNT=1
E_ARGCOUNT=65

if [ $# -ne $ARGCOUNT ]
then
    echo "${#} arguments."
    usage $0
    exit $E_ARGCOUNT
fi

function fmount ()
{
    sshfs -o idmap=user ${1} ~/far_projects
}


fmount ${1}
