#!/usr/bin/env bash
# -*- mode: shell-script; -*-

# Created: 2010-09-17
# mount remote folder locally(~/far_projects) using sshfs; alias

function usage() {     # let the user know how to use this
    echo USAGE: "$1 <$USER@remote:/projects>"
}

ARGCOUNT=1
E_ARGCOUNT=65

if [ $# -ne $ARGCOUNT ]
then
    echo "${#} arguments."
    usage $0
    exit $E_ARGCOUNT
fi

function fmount ()
{
    sshfs -o idmap=user ${1} ~/far_projects
}


fmount ${1}
