#!/bin/sh
# modify "S*L2" to match filename pattern of SeaWiFS files
# Example filename: S1999365235959.L2
cat $1 | while read NAME 
do
  YYYY=`echo $NAME |cut -c2-5`
  DDD=`echo $NAME |cut -c6-8`

  datestring=`$SEADAS/bin/jd2date $DDD $YYYY`
  month=`echo $datestring |cut -c1-2`
  day=`echo $datestring |cut -c3-4`
  
#  per=$((${DDD}/365))
#  pngfile=${day}${month}${YYYY}.png
#  echo ${YYYY} ${DDD} -- ${day}  ${month} ${YYYY} #>> $1

  echo ${YYYY} ${DDD}

done 
