#!/bin/bash
# -*- mode: sh; -*-

for filename in $@; do
    base="${filename%.[^.]*}"
    ext="${filename:${#base} + 1}"

    convert ${filename}  -resize 1240x1750 -compose Copy -gravity \
            center -extent 1240x1750 -units PixelsPerInch -density 300 ${base}.pdf
done
