#!/usr/bin/env python
# -*- mode: python; coding: utf-8-unix; -*-
"""Run a given command in multiple directories.

Example:
 - To run 'ls -l' command on /foo/bar & /foo/bax
   mdr -d /foo/bar /foo/baz -- ls -l

   List of directories can be placed file called 'dirlist'
"""

import sys
import argparse
import os.path
import subprocess
import contextlib


@contextlib.contextmanager
def keep_cwd():
    cwd = os.getcwd()
    try:
        yield
    finally:
        os.chdir(cwd)


def arg_parse(dirs=None, cmd=None):
    dir_list = 'dirlist'
    if dirs is None:
        if os.path.exists(os.path.join('.', dir_list)):
            dirs = open(dir_list, 'r').read().split()
        else:
            print(
                'NOTE: No dirlist file found. running only in current directory'
            )
            dirs = [os.getcwd()]

    for d in dirs:
        with keep_cwd():
            try:
                os.chdir(d)
            except OSError as e:
                print(e, 'Skipping')
                pass
            print('\nrunning "%s" in "%s ":' % (' '.join(cmd), os.getcwd()))
            try:
                p = subprocess.Popen(cmd, shell=True)
                p.wait()
            except (OSError, KeyboardInterrupt) as e:
                print(e)
                if p.poll() == None:
                    p.kill()


def main(args=None):
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawTextHelpFormatter, description=__doc__)
    parser.add_argument('-d', '--dirs', nargs='*', action='store')
    parser.add_argument('cmd', nargs='+')

    arg_parse(**vars(parser.parse_args(args)))


if __name__ == '__main__':
    main()
