#!/bin/bash
# http://stackoverflow.com/a/10244698/399964

iface="eth0"            # which interface to bring up/down
internal=$(
    /sbin/ifconfig "$iface" |
        awk -F'(inet add?r:| +|:)' '/inet add?r/{print $3}'
        )

if [[ ! $internal =~ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]; then
    sudo /sbin/ifconfig "$iface" up
    printf ":: iface brought up: %s\n" "$iface"
else
    sudo /sbin/ifconfig "$iface" down
    printf ":: iface brought down: %s\n" "$iface"
fi
