#!/usr/bin/env bash
# pdfcrop generates another file without replacing. this just replaces the original.

function split-path () {
    fullpath=$@
    filename="${fullpath##*/}"                      # Strip longest match of */ from start
    dir="${fullpath:0:${#fullpath} - ${#filename}}" # Substring from 0 thru pos of filename
    base="${filename%.[^.]*}"                       # Strip shortest match of . plus at least one non-dot char from end
    ext="${filename:${#base} + 1}"                  # Substring from len of base thru end
    if [[ -z "$base" && -n "$ext" ]]; then          # If we have an extension and no base, it's really the base
        base=".$ext"
        ext=""
    fi
}

for f in $@; do
    echo backing up...
    split-path $f
    cp ${base}.${ext}  ${base}_ori.${ext}
    pdfcrop $f

    #
    mv ${base}-crop.${ext}  ${base}.${ext}
done
