#!/usr/bin/env bash
# pdfcrop generates another file without replacing. this just replaces the original.

THIS_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $THIS_FILE_DIR/blib.sh

for f in $@; do
    echo backing up...
    split-path $f
    cp ${base}.${ext}  ${base}_ori.${ext}
    pdfcrop $f

    #
    echo "Renaming to original.."
    mv ${base}-crop.${ext}  ${base}.${ext}
done
