#!/usr/bin/env bash
# pdfcrop generates another file without replacing. this just replaces the original.

THIS_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $THIS_FILE_DIR/blib.sh

for f in $@; do
    split-path $f
    echo backing up... "${base}.${ext} ==>  ${base}_ori.${ext}"
    cp ${base}.${ext}  ${base}_ori.${ext}

    pdftk $f cat 1east output ${base}-rot.pdf
    #
    mv ${base}-rot.${ext}  ${base}.${ext}
done
