#!/usr/bin/env bash
# pdfcrop generates another file without replacing. this just replaces the original.

THIS_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $THIS_FILE_DIR/blib.sh

for f in $@; do
    split-path $f
    # echo backing up... "${base}.${ext} ==>  ${base}_ori.${ext}"
    # cp ${base}.${ext}  ${base}_ori.${ext}

    # pdftk $f cat 1west output ${base}-rot.pdf
    pdf90 $f

    mv ${base}.${ext} ${base}_ori.${ext}
    mv ${base}-rotated90.${ext}  ${base}.${ext}
done
