#!/bin/sh

########################
## using “convert” from ImageMagick to do ps convert into PNG
#########################

echo PS convert to PNG, please wait the process

ext=$1
out_ext=$2

for INP in *.$ext
do
    newname=`basename $INP .$ext`
    convert -density 150 -geometry 100% $INP $INP.png
    echo ” convert $INP to $newname.png completed”
done
echo ” process ended, please check your graphical files”

#something I changed on labubu
