#!/usr/bin/env bash
## Copyright (C) Yagnesh Raghava Yakkala. http://yagnesh.org
## License: GPL v3 or later

if [ $# -lt 1 ]
then
    echo "   ***NO ARGS***  atleast one needed"
    echo "$0 <file/Pattern> <localDirName>"
    exit
fi
##


case `hostname` in
    okho* )
        echo "not implimented yet"
        ;;
    amur* )
        scp -r $vlubu:$1 ${2:-.}
        ;;
    * )
        echo "not the hostname I am aware of"
        ;;
esac


## Local Variables:
## mode: sh
## End:
