#!/usr/bin/env bash
# -*- mode: shell-script; -*-
# Author: Yagnesh Raghava Yakkala
# DATE: 2010-09-09
# Purpose: Repeat the command n times

local i max
max=$1; shift;
for ((i=1; i <= max ; i++)); do  # --> C-like syntax
    eval "$@";
done
