#!/usr/bin/env bash
# pdfcrop generates another file without replacing. this just replaces the original.

THIS_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $THIS_FILE_DIR/blib.sh

for f in $@; do
    split-path $f
    orifile=${base}_ori.${ext}

    if [ -f ${orifile} ]; then
        mv ${base}_ori.${ext} ${base}.${ext}
    else
        echo "no original file $orifile is not available"
    fi

done
